/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateAttributeArgs } from "./CreateAttributeArgs";
import { UpdateAttributeArgs } from "./UpdateAttributeArgs";
import { DeleteAttributeArgs } from "./DeleteAttributeArgs";
import { AttributeFindManyArgs } from "./AttributeFindManyArgs";
import { AttributeFindUniqueArgs } from "./AttributeFindUniqueArgs";
import { Attribute } from "./Attribute";
import { ProductFindManyArgs } from "../../product/base/ProductFindManyArgs";
import { Product } from "../../product/base/Product";
import { AttributeService } from "../attribute.service";

@graphql.Resolver(() => Attribute)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class AttributeResolverBase {
  constructor(
    protected readonly service: AttributeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Attribute",
    action: "read",
    possession: "any",
  })
  async _attributesMeta(
    @graphql.Args() args: AttributeFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Attribute])
  @nestAccessControl.UseRoles({
    resource: "Attribute",
    action: "read",
    possession: "any",
  })
  async attributes(
    @graphql.Args() args: AttributeFindManyArgs
  ): Promise<Attribute[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Attribute, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Attribute",
    action: "read",
    possession: "own",
  })
  async attribute(
    @graphql.Args() args: AttributeFindUniqueArgs
  ): Promise<Attribute | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Attribute)
  @nestAccessControl.UseRoles({
    resource: "Attribute",
    action: "create",
    possession: "any",
  })
  async createAttribute(
    @graphql.Args() args: CreateAttributeArgs
  ): Promise<Attribute> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Attribute)
  @nestAccessControl.UseRoles({
    resource: "Attribute",
    action: "update",
    possession: "any",
  })
  async updateAttribute(
    @graphql.Args() args: UpdateAttributeArgs
  ): Promise<Attribute | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Attribute)
  @nestAccessControl.UseRoles({
    resource: "Attribute",
    action: "delete",
    possession: "any",
  })
  async deleteAttribute(
    @graphql.Args() args: DeleteAttributeArgs
  ): Promise<Attribute | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Product])
  @nestAccessControl.UseRoles({
    resource: "Product",
    action: "read",
    possession: "any",
  })
  async products(
    @graphql.Parent() parent: Attribute,
    @graphql.Args() args: ProductFindManyArgs
  ): Promise<Product[]> {
    const results = await this.service.findProducts(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
