/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BrandWhereUniqueInput } from "../../brand/base/BrandWhereUniqueInput";
import {
  ValidateNested,
  IsOptional,
  IsJSON,
  IsString,
  IsNumber,
} from "class-validator";
import { Type } from "class-transformer";
import { CartUpdateManyWithoutProductsInput } from "./CartUpdateManyWithoutProductsInput";
import { GraphQLJSONObject } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { OrderItemUpdateManyWithoutProductsInput } from "./OrderItemUpdateManyWithoutProductsInput";
@InputType()
class ProductUpdateInput {
  @ApiProperty({
    required: false,
    type: () => BrandWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => BrandWhereUniqueInput)
  @IsOptional()
  @Field(() => BrandWhereUniqueInput, {
    nullable: true,
  })
  brandid?: BrandWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => CartUpdateManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => CartUpdateManyWithoutProductsInput)
  @IsOptional()
  @Field(() => CartUpdateManyWithoutProductsInput, {
    nullable: true,
  })
  carts?: CartUpdateManyWithoutProductsInput;

  @ApiProperty({
    required: false,
  })
  @IsJSON()
  @IsOptional()
  @Field(() => GraphQLJSONObject, {
    nullable: true,
  })
  categoryid?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  image?: string;

  @ApiProperty({
    required: false,
    type: () => OrderItemUpdateManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => OrderItemUpdateManyWithoutProductsInput)
  @IsOptional()
  @Field(() => OrderItemUpdateManyWithoutProductsInput, {
    nullable: true,
  })
  orderItems?: OrderItemUpdateManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  price?: number;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  productname?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  sku?: string | null;
}
export { ProductUpdateInput };
